apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: default-cluster

deploy:
  helm:
      releases:

      # Ingress NGINX.
      - createNamespace: true
        name: ingress-nginx
        namespace: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
      
      # Cert Manager.
      - createNamespace: true
        name: cert-manager
        namespace: cert-manager
        remoteChart: cert-manager
        repo: https://charts.jetstack.io
        setValues:
          installCRDs: true

      # Longhorn.
      - createNamespace: true
        name: longhorn
        namespace: longhorn-system
        remoteChart: longhorn
        repo: https://charts.longhorn.io

      # PostgreSQL.
      - createNamespace: true
        name: postgres
        namespace: postgres
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        setValues:
          primary:
            persistence:
              size: 20Gi

manifests:
  rawYaml:
    - https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.crds.yaml
    - k8s/letsencrypt.yaml
